sonar.projectKey=mustafagenc_homepage
sonar.organization=mustafa-genc

sonar.projectName=homepage
sonar.projectVersion=2.0.1-alpha


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.